an:
  main_1_0: 17
  marketing: 0
  server: 42
ar:
  main_1_0: 85
  marketing: 0
  server: 74
be-BY:
  main_1_0: 23
  marketing: 0
  server: 77
bg-BG:
  main_1_0: 12
  marketing: 0
  server: 10
ca:
  main_1_0: 16
  marketing: 0
  server: 29
cmn:
  main_1_0: 7
  marketing: 0
  server: 5
cs:
  main_1_0: 52
  marketing: 0
  server: 51
da:
  main_1_0: 25
  marketing: 0
  server: 42
de:
  main_1_0: 98
  marketing: 0
  server: 80
el:
  main_1_0: 38
  marketing: 0
  server: 62
en-BE:
  main_1_0: 0
  marketing: 0
  server: 0
en-NL:
  main_1_0: 0
  marketing: 0
  server: 0
en-US: {}
eo:
  main_1_0: 21
  marketing: 0
  server: 42
es:
  main_1_0: 100
  marketing: 99
  server: 93
es-AR:
  main_1_0: 0
  marketing: 0
  server: 0
fa-IR:
  main_1_0: 1
  marketing: 0
  server: 3
fi:
  main_1_0: 11
  marketing: 0
  server: 6
fr:
  main_1_0: 96
  marketing: 0
  server: 91
fr-BE:
  main_1_0: 0
  marketing: 0
  server: 0
ga-IE:
  main_1_0: 66
  marketing: 0
  server: 39
gl:
  main_1_0: 13
  marketing: 0
  server: 17
he:
  main_1_0: 11
  marketing: 0
  server: 19
he-IL: {}
hi:
  main_1_0: 0
  marketing: 0
  server: 0
hi-IN: {}
hr:
  main_1_0: 6
  marketing: 0
  server: 5
hu:
  main_1_0: 30
  marketing: 0
  server: 51
id:
  main_1_0: 14
  marketing: 0
  server: 25
io:
  main_1_0: 0
  marketing: 0
  server: 1
it:
  main_1_0: 66
  marketing: 0
  server: 69
it-CH:
  main_1_0: 0
  marketing: 0
  server: 0
it-IT: {}
ja:
  main_1_0: 17
  marketing: 0
  server: 31
km:
  main_1_0: 12
  marketing: 0
  server: 23
ko:
  main_1_0: 76
  marketing: 0
  server: 39
ko-KR: {}
lt:
  main_1_0: 28
  marketing: 0
  server: 6
lv:
  main_1_0: 0
  marketing: 0
  server: 0
mi:
  main_1_0: 3
  marketing: 0
  server: 1
mk:
  main_1_0: 11
  marketing: 0
  server: 26
ml:
  main_1_0: 13
  marketing: 0
  server: 24
ml-IN:
  main_1_0: 0
  marketing: 0
  server: 0
nb-NO:
  main_1_0: 0
  marketing: 0
  server: 0
nl: {}
nl-NL:
  main_1_0: 33
  marketing: 2
  server: 73
pl:
  main_1_0: 47
  marketing: 0
  server: 20
pt-BR:
  main_1_0: 98
  marketing: 0
  server: 93
pt-PT:
  main_1_0: 0
  marketing: 0
  server: 2
ro:
  main_1_0: 36
  marketing: 0
  server: 57
ru:
  main_1_0: 21
  marketing: 0
  server: 15
ru-RU: {}
sk:
  main_1_0: 17
  marketing: 0
  server: 42
sl:
  main_1_0: 22
  marketing: 0
  server: 46
sr:
  main_1_0: 82
  marketing: 0
  server: 84
sr-RS:
  main_1_0: 21
  marketing: 0
  server: 68
sv:
  main_1_0: 17
  marketing: 0
  server: 42
te:
  main_1_0: 8
  marketing: 0
  server: 10
te-IN: {}
th: {}
th-TH:
  main_1_0: 0
  marketing: 0
  server: 0
tr:
  main_1_0: 81
  marketing: 0
  server: 73
uk:
  main_1_0: 68
  marketing: 0
  server: 44
ur:
  main_1_0: 0
  marketing: 0
  server: 0
ur-PK:
  main_1_0: 0
  marketing: 0
  server: 0
vi:
  main_1_0: 11
  marketing: 0
  server: 15
zh-TW:
  main_1_0: 98
  marketing: 97
  server: 100
